// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRxliF6Rrv8TCXYVxi213lF6GTP459ug',
    appId: '1:834279400786:web:6c12ceae4645f576bd868b',
    messagingSenderId: '834279400786',
    projectId: 'my-app-english-c87dd',
    authDomain: 'my-app-english-c87dd.firebaseapp.com',
    databaseURL: 'https://my-app-english-c87dd-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-english-c87dd.firebasestorage.app',
    measurementId: 'G-N9ZT2NZB7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV0VYV96IA0shZpcY8vlX6-WDpaI6Ujpk',
    appId: '1:834279400786:android:285732c8ef83b6abbd868b',
    messagingSenderId: '834279400786',
    projectId: 'my-app-english-c87dd',
    databaseURL: 'https://my-app-english-c87dd-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-english-c87dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5d3cRrbdrTlrjWwJJG69Q0UnEDYCdwKI',
    appId: '1:834279400786:ios:60f9037eb7e7ef54bd868b',
    messagingSenderId: '834279400786',
    projectId: 'my-app-english-c87dd',
    databaseURL: 'https://my-app-english-c87dd-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-english-c87dd.firebasestorage.app',
    iosBundleId: 'com.example.bearGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5d3cRrbdrTlrjWwJJG69Q0UnEDYCdwKI',
    appId: '1:834279400786:ios:60f9037eb7e7ef54bd868b',
    messagingSenderId: '834279400786',
    projectId: 'my-app-english-c87dd',
    databaseURL: 'https://my-app-english-c87dd-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-english-c87dd.firebasestorage.app',
    iosBundleId: 'com.example.bearGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoRxliF6Rrv8TCXYVxi213lF6GTP459ug',
    appId: '1:834279400786:web:cbc3c5d8f898d9d8bd868b',
    messagingSenderId: '834279400786',
    projectId: 'my-app-english-c87dd',
    authDomain: 'my-app-english-c87dd.firebaseapp.com',
    databaseURL: 'https://my-app-english-c87dd-default-rtdb.firebaseio.com',
    storageBucket: 'my-app-english-c87dd.firebasestorage.app',
    measurementId: 'G-XGB6PR5DNW',
  );
}
